import { afterEach, describe, expect, it, vi } from 'vitest';
import { LunarUtil, Solar } from 'lunar-typescript';
import { semanticHash, stableId } from '../integrated-report/canonical-hash';
import { syntheticBazi } from '../../tests/fixtures/integrated-advantage/synthetic-bazi';
import { BirthSupportAssessmentSchema, prepareBirthInput, type BirthInputV2 } from './input-v2';
import { BaziSignalSnapshotSchema, type BaziSignalSnapshot } from './signal-schema';
import { ChartVariantEnumerationSchema, enumerateChartVariants, type CompleteChartVariants } from './time-variants';
import * as calendar from './time-variant-calendar';

const support = { reportedTimeBasis: 'beijing_standard', overseasDeclared: false };
const input: BirthInputV2 = {
  schemaVersion: 'birth-input-v2', birthDate: '2025-02-03', calendarType: 'solar', isLeapMonth: false,
  timezone: 'Asia/Shanghai', timeBasis: 'standard_clock', reportedPrecision: 'exact', birthTime: '22:10', timeRange: null,
};
const unknown = (birthDate = input.birthDate): BirthInputV2 => ({ ...input, birthDate, birthTime: null, reportedPrecision: 'unknown' });
const range = (birthDate: string, start: string, end: string, endDayOffset: 0 | 1 = 0): BirthInputV2 => ({ ...input, birthDate, birthTime: null, reportedPrecision: 'range', timeRange: { start, end, endDayOffset } });
function complete(value: BirthInputV2): CompleteChartVariants {
  const result = enumerateChartVariants(value, support);
  expect(result.status).toBe('complete');
  if (result.status !== 'complete') throw new Error(result.status);
  return result;
}
function reseal(snapshot: BaziSignalSnapshot) {
  snapshot.meta.artifactHash = semanticHash(snapshot);
  return BaziSignalSnapshotSchema.safeParse(snapshot);
}
// Public identifiers can be regenerated by any caller; they are not proof of coverage.
function reindex(result: CompleteChartVariants) {
  for (const s of result.segments) s.segmentId = stableId('chart-segment', {
    start: s.start, end: s.end, startInclusive: s.startInclusive, endInclusive: s.endInclusive, variantId: s.variantId,
  });
  for (const v of result.variants) v.segmentIds = result.segments.filter(s => s.variantId === v.variantId).map(s => s.segmentId);
  return result;
}
afterEach(() => vi.restoreAllMocks());

describe('historical standard-clock scope regression', () => {
  const edges = [
    '1900-01-01', '1900-12-31', '1901-01-01', '1919-04-12', '1919-04-13', '1919-09-30', '1919-10-01',
    '1949-05-27', '1949-05-28', '1949-12-31', '1950-01-01', '1985-12-31', '1986-01-01', '1991-12-31', '1992-01-01',
  ];
  it.each(edges)('does not block verified fixed UTC+08 fields merely because of date %s', birthDate => {
    expect(prepareBirthInput({ ...input, birthDate }, support).status).toBe('supported');
    expect(prepareBirthInput(unknown(birthDate), support).status).toBe('supported');
    expect(prepareBirthInput(unknown(birthDate), { ...support, reportedTimeBasis: 'historical_unverified' }).status).toBe('unavailable');
  });
  // Literal transition dates independently expanded from IANA PRC rules, not a production helper.
  it.each([
    ['1986-05-04', '1986-09-14'], ['1987-04-12', '1987-09-13'], ['1988-04-17', '1988-09-11'],
    ['1989-04-16', '1989-09-17'], ['1990-04-15', '1990-09-16'], ['1991-04-14', '1991-09-15'],
  ])('keeps standard fields distinct from unverified civil records around %s / %s', (start, end) => {
    for (const date of [start, end]) {
      const [y, m, d] = date.split('-').map(Number);
      for (const offset of [-1, 0, 1]) {
        const birthDate = Solar.fromYmd(y, m, d).nextDay(offset).toYmd();
        for (const value of [unknown(birthDate), range(birthDate, '01:59', '03:01'), range(birthDate, '23:59', '00:00', 1),
          ...['00:00', '01:00', '01:59', '02:00', '02:59', '03:00'].map(birthTime => ({ ...input, birthDate, birthTime }))]) {
          expect(prepareBirthInput(value, support).status).toBe('supported');
          expect(prepareBirthInput(value, { ...support, reportedTimeBasis: 'historical_unverified' })).toMatchObject({ status: 'unavailable', input: null, timeConfidence: null });
        }
      }
    }
  });
  it('does not perform an implicit DST shift on fixed-standard summer dates', () => {
    const value = { ...input, birthDate: '1987-08-03', birthTime: '00:30' };
    const result = complete(value);
    expect(result.coverage.start).toBe('1987-08-03T00:30:00+08:00');
    expect(result.variants[0].chart.hourBranch).toBe('子');
    expect(complete({ ...value, calendarType: 'lunar' }).coverage.start).toBe('1987-09-25T00:30:00+08:00');
    expect(complete({ ...value, calendarType: 'lunar', birthDate: '1987-06-01', isLeapMonth: true }).coverage.start).toBe('1987-07-26T00:30:00+08:00');
  });
  it('rejects an unavailable historical assessment contradicting an explicit standard declaration', () => {
    expect(BirthSupportAssessmentSchema.safeParse({ ...support, status: 'unavailable', reasonCode: 'historical_time_basis_unverified' }).success).toBe(false);
  });
});

describe('partial chart consumer contract', () => {
  function partial() {
    const snapshot = syntheticBazi({ stableThemes: ['analysis_research'] }).snapshot;
    snapshot.timeConfidence = 'unknown';
    snapshot.status = 'partial';
    snapshot.chartVariants[0].knownPillars = ['year', 'month', 'day'];
    return snapshot;
  }
  it('permits stable non-hour signals only within an explicitly partial unknown snapshot', () => {
    expect(reseal(partial()).success).toBe(true);
    const forged = partial();
    forged.status = 'available';
    expect(reseal(forged).success).toBe(false);
  });
  it('rejects unknown variants that silently omit the day pillar', () => {
    const forged = partial();
    forged.chartVariants[0].knownPillars = ['year', 'month'];
    expect(reseal(forged).success).toBe(false);
  });
  it('rejects known-time variants that silently omit the hour pillar', () => {
    const forged = syntheticBazi({ stableThemes: ['analysis_research'] }).snapshot;
    forged.chartVariants[0].knownPillars = ['year', 'month', 'day'];
    expect(reseal(forged).success).toBe(false);
  });
});

describe('serialized complete coverage is semantically verified', () => {
  it('rejects an internally consistent morning-only unknown result', () => {
    const forged = complete(unknown('2000-06-15'));
    forged.segments = forged.segments.slice(0, 4);
    forged.coverage.end = forged.segments.at(-1)!.end;
    expect(ChartVariantEnumerationSchema.safeParse(reindex(forged)).success).toBe(false);
  });
  it('rejects a range mislabeled exact and a cross-shichen range mislabeled same-shichen', () => {
    const forged = complete(range('2000-06-15', '14:50', '15:10'));
    forged.timeConfidence = 'exact';
    expect(ChartVariantEnumerationSchema.safeParse(forged).success).toBe(false);
    forged.timeConfidence = 'approximate_same_shichen';
    expect(ChartVariantEnumerationSchema.safeParse(forged).success).toBe(false);
  });
  it('rejects a rehashed segment merging both sides of 立春 into the first chart', () => {
    const forged = complete(range('2025-02-03', '22:10', '22:11'));
    forged.variants = [forged.variants[0]];
    forged.segments = [forged.segments[0]];
    forged.segments[0].end = forged.coverage.end;
    forged.segments[0].endInclusive = true;
    forged.stablePillars = { ...forged.variants[0].chart.pillars };
    expect(ChartVariantEnumerationSchema.safeParse(reindex(forged)).success).toBe(false);
  });
  it('rejects correct hash and references attached to the wrong civil date', () => {
    const forged = complete({ ...input, birthDate: '2000-06-15' });
    for (const s of forged.segments) {
      s.start = s.start.replace('2000-06-15', '2000-06-16');
      s.end = s.end.replace('2000-06-15', '2000-06-16');
      s.calculationPoint = s.start;
    }
    forged.coverage.start = forged.segments[0].start;
    forged.coverage.end = forged.segments[0].end;
    expect(ChartVariantEnumerationSchema.safeParse(reindex(forged)).success).toBe(false);
  });
});

// Literal shichen expectations; catches an odd-hour offset or missed closed endpoint.
describe('every shichen boundary and midnight', () => {
  it.each([
    ['00:59', '01:00', '01:01', '子', '丑'], ['02:59', '03:00', '03:01', '丑', '寅'],
    ['04:59', '05:00', '05:01', '寅', '卯'], ['06:59', '07:00', '07:01', '卯', '辰'],
    ['08:59', '09:00', '09:01', '辰', '巳'], ['10:59', '11:00', '11:01', '巳', '午'],
    ['12:59', '13:00', '13:01', '午', '未'], ['14:59', '15:00', '15:01', '未', '申'],
    ['16:59', '17:00', '17:01', '申', '酉'], ['18:59', '19:00', '19:01', '酉', '戌'],
    ['20:59', '21:00', '21:01', '戌', '亥'], ['22:59', '23:00', '23:01', '亥', '子'],
  ])('%s / %s / %s', (before, at, after, oldBranch, newBranch) => {
    for (const [birthTime, expected] of [[before, oldBranch], [at, newBranch], [after, newBranch]]) {
      expect(complete({ ...input, birthDate: '2000-06-15', birthTime }).variants[0].chart.hourBranch).toBe(expected);
    }
    const result = complete(range('2000-06-15', before, at));
    expect(result.variants.map(v => v.chart.hourBranch)).toEqual([oldBranch, newBranch]);
    expect(result.segments.at(-1)).toMatchObject({ start: `2000-06-15T${at}:00+08:00`, end: `2000-06-15T${at}:00+08:00`, endInclusive: true });
    expect(complete(range('2000-06-15', at, after)).variants).toHaveLength(1);
  });
  it.each([
    ['2025-02-03', '22:59', '癸卯', '癸亥'], ['2025-02-03', '23:00', '癸卯', '壬子'],
    ['2025-02-03', '23:59', '癸卯', '壬子'], ['2025-02-04', '00:00', '甲辰', '甲子'],
    ['2025-02-04', '00:59', '甲辰', '甲子'], ['2025-02-04', '01:00', '甲辰', '乙丑'],
  ])('retains the existing project sect=2 day/hour rule at %s %s', (birthDate, birthTime, day, hour) => {
    expect(complete({ ...input, birthDate, birthTime }).variants[0].chart.pillars).toMatchObject({ day, hour });
  });
});

describe('short solar term segments, dedupe and lunar equivalence', () => {
  it('retains a one-second pre-term segment and a closed term endpoint', () => {
    // Instrument only term placement; use real calendar facts on either side of 2025 立春.
    const original = calendar.canonicalChartAt;
    vi.spyOn(calendar, 'solarTermOffsets').mockReturnValue([22 * 3600 + 10 * 60 + 1]);
    vi.spyOn(calendar, 'canonicalChartAt').mockImplementation((base, seconds, known) => original(base, seconds + 27, known));
    const result = complete(range('2025-02-03', '22:10', '22:11'));
    expect(result.segments[0].end).toBe('2025-02-03T22:10:01+08:00');
    expect(result.variants).toHaveLength(2);
    vi.spyOn(calendar, 'solarTermOffsets').mockReturnValue([22 * 3600 + 11 * 60]);
    vi.spyOn(calendar, 'canonicalChartAt').mockImplementation((base, seconds, known) => original(base, seconds - 32, known));
    const endpoint = complete(range('2025-02-03', '22:10', '22:11'));
    expect(endpoint.variants).toHaveLength(2);
    expect(endpoint.segments.at(-1)).toMatchObject({ start: '2025-02-03T22:11:00+08:00', end: '2025-02-03T22:11:00+08:00', endInclusive: true });
  });
  it('applies the cap after dedupe even with over 32 distinct segments', () => {
    vi.spyOn(calendar, 'solarTermOffsets').mockReturnValue(Array.from({ length: 40 }, (_, i) => i + 1));
    const result = complete(unknown('2000-06-15'));
    expect(result.segments.length).toBeGreaterThan(32);
    expect(result.variants).toHaveLength(1);
    expect(result.variants[0].segmentIds).toHaveLength(result.segments.length);
  });
  it.each(['exact', 'range', 'unknown'] as const)('preserves leap-month solar-term semantics for %s', precision => {
    // 2023 leap lunar February 15 == April 5, 清明 falls within this day.
    const solar = precision === 'unknown' ? unknown('2023-04-05')
      : precision === 'range' ? range('2023-04-05', '00:00', '23:59') : { ...input, birthDate: '2023-04-05', birthTime: '12:00' };
    const lunar = { ...solar, calendarType: 'lunar' as const, birthDate: '2023-02-15', isLeapMonth: true };
    expect(complete(lunar)).toEqual(complete(solar));
    if (precision !== 'exact') expect(complete(lunar).stablePillars.month).toBeNull();
  });
});


describe('calendar extremes and independently asserted term-side states', () => {
  it.each([1900, 1901, 1919, 1949, 1950, 1986, 1991, 2100])('covers all twelve month-switching days in standard-clock year %i', year => {
    const table = Solar.fromYmd(year, 6, 15).getLunar().getJieQiTable();
    const terms = LunarUtil.JIE_QI_IN_USE.filter((_, i) => i % 2 === 0).map(key => table[key]).filter(term => term.getYear() === year);
    expect(terms).toHaveLength(12);
    for (const term of terms) {
      const result = complete(unknown(term.toYmd()));
      expect(result.variants).toHaveLength(2);
      expect(result.stablePillars.month).toBeNull();
      expect(result.variants.every(v => v.chart.pillars.hour === null)).toBe(true);
    }
  });
  it('switches at the exact library term second, with no one-second gap', () => {
    const base = Solar.fromYmd(2025, 2, 3);
    const result = complete(range('2025-02-03', '22:10', '22:11'));
    for (const [second, year, month] of [[79827, '甲辰', '丁丑'], [79828, '乙巳', '戊寅'], [79829, '乙巳', '戊寅']] as const) {
      const stamp = calendar.standardClockTimestamp(base, second);
      const segments = result.segments.filter(s => stamp >= s.start && (stamp < s.end || (stamp === s.end && s.endInclusive)));
      expect(segments).toHaveLength(1);
      const chart = result.variants.find(v => v.variantId === segments[0].variantId)!.chart;
      expect(chart.pillars).toMatchObject({ year, month });
      expect(calendar.canonicalChartAt(base, second, true).pillars).toMatchObject({ year, month });
    }
  });
  it('retains the pre-noon term state instead of taking the noon chart as all-day stability', () => {
    // 2023 立春 is in the morning; complements the 2025 late-evening regression.
    const result = complete(unknown('2023-02-04'));
    expect(result.variants.map(v => v.chart.pillars.year)).toEqual(['壬寅', '癸卯']);
    expect(result.variants.map(v => v.chart.pillars.month)).toEqual(['癸丑', '甲寅']);
    expect(result.stablePillars.year).toBeNull();
    expect(result.stablePillars.month).toBeNull();
    expect(result.stablePillars.hour).toBeNull();
  });
});
